### ISSUE TITLE
1.16.3 support

### ISSUE THREAD

**Issue by KasperiP** [TechnicianLP/ReAuth#30] opened 2020-09-15 15:00 UTC
Fabric reauth doesnt work on 1.16.3. It launches the game but if you press reauth button in multiplayer menu your game crashes.

**Comment by KasperiP** [comment] 2020-09-15 15:04
Description: Rendering screen

java.lang.IncompatibleClassChangeError: Expecting non-static method technicianlp.reauth.gui.AuthScreen.method_25300(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Ljava/lang/String;III)V
	at technicianlp.reauth.gui.AuthScreen.method_25394(AuthScreen.java:94)
	at net.minecraft.class_757.method_3192(class_757.java:824)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Comment by StackDoubleFlow** [comment] 2020-09-21 00:29
The same issue also happens on 1.16.2

**Comment by TechnicianLP** [comment] 2020-09-21 14:30
1.16.2 should work with the 1.16.2 version of the mod (available here: https://www.curseforge.com/minecraft/mc-mods/reauth-fabric)
Same is likely the case for 1.16.3 but that requires a rebuild

**Comment by IMS212** [comment] 2020-11-02 22:41
Should this be extended to 1.16.4, which changed the auth system it seems?

**Comment by TechnicianLP** [comment] 2020-11-08 15:41
No the 1.16.4 Crash was unrelated to this one and caused by a change in the authlib.
This Issue has already been fixed in a previous version.

**Closed by TechnicianLP** 2020-11-08 15:41 UTC
